# SPDX-License-Identifier: Apache-2.0
"""Wire a repo up (offline, idempotent): a git post-commit hook + a managed AGENTS.md
block, optionally a Claude PostToolUse hook. Also the pip/curl bootstrap that vendors a
self-contained copy of the package into the repo. Network is only needed by the curl
bootstrap (install.sh) and `update`."""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys

from .config import register_backend
from .gitutil import git, repo_root
from .version import CANONICAL_REPO, tool_version

DEFAULT_VENDOR_DIR = ".llm_resource_tally/tool"   # code sits beside its data (one dotdir)


def module_dir() -> str:
    """This package's directory (…/llm_resource_tally)."""
    return os.path.dirname(os.path.abspath(__file__))


# ---- invocation -----------------------------------------------------------------
def _module_in_repo(root: str) -> bool:
    md, r = os.path.realpath(module_dir()), os.path.realpath(root)
    return md == r or md.startswith(r + os.sep)


def _rel_dir(root: str) -> str | None:
    """The package dir relative to repo root if vendored/submodule, else None (pip)."""
    return os.path.relpath(module_dir(), root) if _module_in_repo(root) else None


def _run_cmd(rel: str | None) -> str:
    """How a human/hook invokes the tool: run the vendored package dir by path (Python
    executes its __main__.py), or the console script when pip'd (bootstrap only)."""
    return f"python3 {rel}" if rel else "llm_resource_tally"


def _is_pip_install() -> bool:
    md = module_dir()
    return "site-packages" in md or "dist-packages" in md or not _module_in_repo(repo_root())


# ---- vendoring ------------------------------------------------------------------
def _vendor_into(root: str, rel: str) -> str:
    """Copy the package from the running (pip-installed) install into `<root>/<rel>/`,
    then stamp VERSION and ensure the hook script — so the repo is self-contained and
    offline exactly like the curl route. PyPI is only the delivery mechanism."""
    dest = os.path.join(root, rel)
    shutil.copytree(module_dir(), dest, dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    with open(os.path.join(dest, "VERSION"), "w", encoding="utf-8") as fh:
        fh.write(tool_version() + "\n")
    _ensure_hook_file(root, rel)
    return f"vendored the package into {rel}/ (from the installed package)"


# ---- hook script ----------------------------------------------------------------
# Self-locating post-commit written into `<dir>/hooks/` (used when core.hooksPath points
# there). `$here/..` is the package dir, which Python runs via its __main__.py.
SHARED_HOOK = (
    "#!/usr/bin/env bash\n"
    "# llm_resource_tally post-commit — auto-record LLM usage for the commit just made.\n"
    "# Self-locating; best-effort (accounting must never block or fail a commit).\n"
    'here="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)" || exit 0\n'
    'python3 "$here/.." record --commit HEAD >/dev/null 2>&1 || true\n'
)

HOOK_BEGIN = "# >>> llm_resource_tally (managed — regenerated by `install`) >>>"
HOOK_END = "# <<< llm_resource_tally (managed) <<<"


def _ensure_hook_file(root: str, rel: str) -> None:
    """Guarantee `<rel>/hooks/post-commit` exists (write from SHARED_HOOK if missing), so
    core.hooksPath share-mode has something to run."""
    hd = os.path.join(root, rel, "hooks")
    os.makedirs(hd, exist_ok=True)
    p = os.path.join(hd, "post-commit")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(SHARED_HOOK)
    _chmod_x(p)


def _hook_block(rel: str) -> str:
    """Sentinel-wrapped post-commit body calling the vendored package by path. Best-effort
    (`|| true`); resolves the repo root at run time so it is correct from any cwd."""
    return (f"{HOOK_BEGIN}\n"
            f'root="$(git rev-parse --show-toplevel 2>/dev/null)" || root=""\n'
            f'[ -n "$root" ] && python3 "$root/{rel}" record '
            f"--commit HEAD >/dev/null 2>&1 || true\n"
            f"{HOOK_END}")


# ---- small fs/git helpers -------------------------------------------------------
def _chmod_x(path: str) -> None:
    try:
        os.chmod(path, os.stat(path).st_mode | 0o111)
    except OSError:
        pass


def _git_config(root: str, *args: str) -> str:
    try:
        return git("config", *args, cwd=root)
    except subprocess.CalledProcessError:
        return ""


def _read_text(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def _replace_region(text: str, begin: str, end: str, repl: str) -> str:
    if begin in text and end in text:
        s = text.index(begin)
        e = text.index(end, s) + len(end)
        return text[:s] + repl + text[e:]
    return text


def _strip_region(text: str, begin_idx: int, end_str: str) -> str:
    e = text.index(end_str, begin_idx) + len(end_str)
    before, after = text[:begin_idx], text[e:]
    if before.endswith("\n"):
        before = before[:-1]
    if after.startswith("\n"):
        after = after[1:]
    return before + after


# ---- git hook wiring ------------------------------------------------------------
def _hooks_dir_default(root: str) -> str:
    hd = git("rev-parse", "--git-path", "hooks", cwd=root)
    return hd if os.path.isabs(hd) else os.path.join(root, hd)


def _has_active_git_hooks(root: str) -> bool:
    hd = _hooks_dir_default(root)
    if not os.path.isdir(hd):
        return False
    for name in os.listdir(hd):
        if name.endswith(".sample"):
            continue
        p = os.path.join(hd, name)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return True
    return False


def _effective_hooks_dir(root: str, existing_hp: str) -> str:
    if existing_hp:
        return existing_hp if os.path.isabs(existing_hp) else os.path.join(root, existing_hp)
    return _hooks_dir_default(root)


def _wire_hook(root: str, rel: str, mode: str) -> str:
    """auto: share via core.hooksPath if safe (unset + no foreign hooks) else append;
    hookspath: force core.hooksPath; append: force append; none: nothing."""
    if mode == "none":
        return "skipped (--hook-mode none)"
    existing_hp = _git_config(root, "--get", "core.hooksPath")
    shared_dir = f"{rel}/hooks"

    if existing_hp and os.path.normpath(existing_hp) == os.path.normpath(shared_dir):
        _chmod_x(os.path.join(root, shared_dir, "post-commit"))
        return f"already shared via core.hooksPath -> {shared_dir}"

    eff_hook = os.path.join(_effective_hooks_dir(root, existing_hp), "post-commit")
    if os.path.exists(eff_hook) and HOOK_BEGIN in _read_text(eff_hook):
        return _append_hook(root, rel, existing_hp)

    want_shared = mode == "hookspath" or (
        mode == "auto" and not existing_hp and not _has_active_git_hooks(root))
    if want_shared:
        git("config", "core.hooksPath", shared_dir, cwd=root)
        _chmod_x(os.path.join(root, shared_dir, "post-commit"))
        return f"core.hooksPath -> {shared_dir} (committed; shared with everyone who clones)"
    return _append_hook(root, rel, existing_hp)


def _append_hook(root: str, rel: str, existing_hp: str) -> str:
    hd = _effective_hooks_dir(root, existing_hp)
    os.makedirs(hd, exist_ok=True)
    hook = os.path.join(hd, "post-commit")
    where = os.path.relpath(hook, root)
    block = _hook_block(rel)
    if os.path.exists(hook):
        text = _read_text(hook)
        if HOOK_BEGIN in text:
            new = _replace_region(text, HOOK_BEGIN, HOOK_END, block)
            if new == text:
                return f"unchanged ({where})"
            with open(hook, "w", encoding="utf-8") as fh:
                fh.write(new)
            _chmod_x(hook)
            return f"regenerated managed block in {where}"
        if not text.endswith("\n"):
            text += "\n"
        with open(hook, "w", encoding="utf-8") as fh:
            fh.write(text + "\n" + block + "\n")
        _chmod_x(hook)
        return f"appended managed block to existing {where}"
    with open(hook, "w", encoding="utf-8") as fh:
        fh.write("#!/usr/bin/env bash\n" + block + "\n")
    _chmod_x(hook)
    return f"created {where}"


# ---- AGENTS.md wiring -----------------------------------------------------------
AGENTS_BEGIN = ("<!-- BEGIN llm_resource_tally v{version} (managed block — regenerated by "
                "`install`; edits below will be overwritten) -->")
AGENTS_END = "<!-- END llm_resource_tally -->"
AGENTS_BEGIN_RE = re.compile(
    r"<!--\s*BEGIN llm_resource_tally(?:\s+v([0-9][0-9A-Za-z.\-+]*))?.*?-->", re.S)

AGENTS_SNIPPET = """\
## Resource accounting — the LLM compute this work costs (CRITICAL: do this every commit)

Every commit in this repo is produced by an LLM agent; we keep a **measured** per-commit
record of the tokens/model it cost (inference-time, energy & carbon are derived later).

- **After cloning**, wire the hook once (offline, idempotent): `{run} install`
- Thereafter every `git commit` auto-records. To record by hand: `{run} record`
- **At session end** (captures planning/chat that produced no commit): `{run} reconcile && {run} rollup`
- Codex agents: `{run} record --backend codex`
- Other non-Claude agents: `{run} record --backend <name> --transcript <path>`

**Tag what the work was** with `--label` (e.g. `record --label implementation`, or
`reconcile --label planning`) so non-code work is counted and attributable.

Tokens/model are MEASURED from your session transcript (deduped by message id — do NOT
hand-count). The ledger `.llm_resource_tally/ledger/` (at this repo's root) is append-only,
per-session, concurrency-safe, and stores measurements only."""


def _managed_agents_block(run: str, version: str) -> str:
    return (AGENTS_BEGIN.format(version=version) + "\n"
            + AGENTS_SNIPPET.format(run=run) + "\n" + AGENTS_END)


def _install_agents_block(root: str, run: str, version: str, agents_name: str) -> str:
    path = os.path.join(root, agents_name)
    block = _managed_agents_block(run, version)
    if os.path.exists(path):
        text = _read_text(path)
        m = AGENTS_BEGIN_RE.search(text)
        if m and AGENTS_END in text[m.end():]:
            old = m.group(1) or "?"
            e = text.index(AGENTS_END, m.end()) + len(AGENTS_END)
            new_text = text[:m.start()] + block + text[e:]
            if new_text == text:
                return f"already current (v{version})"
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            return (f"regenerated managed block (v{version})" if old == version
                    else f"upgraded managed block v{old} -> v{version}")
        sep = "\n" if text.endswith("\n") else "\n\n"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text + sep + block + "\n")
        return f"appended managed block (v{version})"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# {agents_name}\n\n" + block + "\n")
    return f"created {agents_name} with managed block (v{version})"


# ---- Claude PostToolUse hook wiring (.claude/settings.json) ----------------------
def _claude_hook_cmd(rel: str) -> str:
    return f'python3 "$CLAUDE_PROJECT_DIR/{rel}" hook'


def _claude_settings_path(root: str) -> str:
    return os.path.join(root, ".claude", "settings.json")


def _entry_is_ours(entry: dict) -> bool:
    for h in entry.get("hooks", []) if isinstance(entry, dict) else []:
        c = h.get("command", "") if isinstance(h, dict) else ""
        if "tally" in c and c.rstrip().endswith("hook"):
            return True
    return False


def _wire_claude_hook(root: str, rel: str) -> str:
    import json
    path = _claude_settings_path(root)
    data: dict = {}
    if os.path.exists(path):
        try:
            data = json.loads(_read_text(path)) or {}
        except json.JSONDecodeError:
            return "skipped (.claude/settings.json is not valid JSON — wire it by hand)"
    ptu = data.setdefault("hooks", {}).setdefault("PostToolUse", [])
    if not isinstance(ptu, list):
        return "skipped (unexpected hooks.PostToolUse shape)"
    ptu[:] = [e for e in ptu if not _entry_is_ours(e)]
    cmd = _claude_hook_cmd(rel)
    ptu.append({"matcher": "Bash", "hooks": [{"type": "command", "command": cmd}]})
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    return f"PostToolUse(Bash) -> {cmd}"


def _unwire_claude_hook(root: str) -> str | None:
    import json
    path = _claude_settings_path(root)
    if not os.path.exists(path):
        return None
    try:
        data = json.loads(_read_text(path)) or {}
    except json.JSONDecodeError:
        return None
    ptu = (data.get("hooks") or {}).get("PostToolUse")
    if not isinstance(ptu, list):
        return None
    kept = [e for e in ptu if not _entry_is_ours(e)]
    if len(kept) == len(ptu):
        return None
    data["hooks"]["PostToolUse"] = kept
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    return "removed PostToolUse(Bash) hook from .claude/settings.json"


# ---- commands -------------------------------------------------------------------
def cmd_install(args) -> None:
    root = repo_root()
    from_pip = _is_pip_install()
    if from_pip:
        rel = args.dir or DEFAULT_VENDOR_DIR
        vendor_msg = _vendor_into(root, rel)
    else:
        rel = args.dir or _rel_dir(root)
        vendor_msg = None
    _ensure_hook_file(root, rel)          # guarantee the shared hook script exists
    run = _run_cmd(rel)
    version = tool_version()
    hook_msg = _wire_hook(root, rel, args.hook_mode)
    agents_msg = _install_agents_block(root, run, version, args.agents_file)
    _chmod_x(os.path.join(root, rel, "__main__.py"))
    claude_msg = _wire_claude_hook(root, rel) if args.claude else None
    backends = register_backend(getattr(args, "backend", None))
    print(f"llm_resource_tally v{version} installed in {os.path.basename(root)} [{rel}]")
    if vendor_msg:
        print(f"  vendored   : {vendor_msg}")
    print(f"  hook       : {hook_msg}")
    print(f"  {args.agents_file:<11}: {agents_msg}")
    if claude_msg:
        print(f"  claude hook: {claude_msg}")
    print(f"  backends   : {', '.join(backends)} (passive hook records these; "
          "edit .llm_resource_tally/settings.json to change)")
    print("  ledger     : .llm_resource_tally/ledger/ at repo root (committed; data never touched by install)")
    print(f"commit the changes to share them; run `{run} reconcile && {run} rollup` at session end.")


def cmd_uninstall(args) -> None:
    root = repo_root()
    rel = args.dir or _rel_dir(root)
    msgs = []
    hp = _git_config(root, "--get", "core.hooksPath")
    if rel and hp and os.path.normpath(hp) == os.path.normpath(f"{rel}/hooks"):
        git("config", "--unset", "core.hooksPath", cwd=root)
        msgs.append(f"unset core.hooksPath ({hp})")
    hd = (hp if os.path.isabs(hp) else os.path.join(root, hp)) if hp else _hooks_dir_default(root)
    hook = os.path.join(hd, "post-commit")
    if os.path.exists(hook):
        text = _read_text(hook)
        if HOOK_BEGIN in text:
            s = text.index(HOOK_BEGIN)
            stripped = _strip_region(text, s, HOOK_END)
            if stripped.strip() in ("", "#!/usr/bin/env bash", "#!/bin/sh"):
                os.remove(hook)
                msgs.append(f"removed {os.path.relpath(hook, root)}")
            else:
                with open(hook, "w", encoding="utf-8") as fh:
                    fh.write(stripped)
                msgs.append(f"stripped managed block from {os.path.relpath(hook, root)}")
    path = os.path.join(root, args.agents_file)
    if os.path.exists(path):
        text = _read_text(path)
        m = AGENTS_BEGIN_RE.search(text)
        if m and AGENTS_END in text[m.end():]:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(_strip_region(text, m.start(), AGENTS_END))
            msgs.append(f"stripped managed block from {args.agents_file}")
    claude_removed = _unwire_claude_hook(root)
    if claude_removed:
        msgs.append(claude_removed)
    print("llm_resource_tally uninstalled:" if msgs else "nothing to uninstall.")
    for m in msgs:
        print(f"  - {m}")
    if msgs:
        print("  the .llm_resource_tally/ ledger and the package files were left in place.")


def cmd_update(args) -> None:
    """Re-vendor the latest version from the canonical repo, then re-run install. Needs
    network. The pinned vendored copy keeps working if this fails or the host is gone."""
    root = repo_root()
    rel = _rel_dir(root)
    if rel is None:
        sys.exit("this is a pip install — upgrade with `pip install -U llm_resource_tally` "
                 "then re-run `llm_resource_tally install` to re-vendor.")
    repo = args.repo or CANONICAL_REPO
    ref = args.ref
    url = f"https://raw.githubusercontent.com/{repo}/{ref}/install.sh"
    fetch = ("curl -fsSL" if shutil.which("curl")
             else "wget -qO-" if shutil.which("wget") else None)
    if not fetch:
        sys.exit("error: need curl or wget to update.")
    print(f"updating {rel} from {repo}@{ref} ...")
    env = {**os.environ, "RT_REPO": repo, "RT_REF": ref, "RT_DIR": rel}
    subprocess.run(f'{fetch} "{url}" | sh', shell=True, cwd=root, env=env, check=True)
